In [3]:
import numpy as np
a= np.random.randn(12288,150)
b= np.random.randn(150,45)
c= np.dot(a,b)
print(c.shape)

(12288, 45)


In [9]:
import numpy as np
a= np.random.randn(3,3)
b= np.random.randn(3,1)
c= a*b
print(a)
print(b)
print(c)


[[-0.45993049  0.35638607 -1.63633946]
 [-1.87973921 -1.27777559 -0.73077922]
 [ 0.1460325   0.25655269 -1.23495757]]
[[-1.13893476]
 [ 1.06173815]
 [ 0.54739808]]
[[ 0.52383083 -0.40590048  1.86368389]
 [-1.99579083 -1.35666309 -0.77589617]
 [ 0.07993791  0.14043645 -0.6760134 ]]
