In [1]:
import numpy as np 

In [2]:
a = np.random.randn(5) #stores 5 random Gaussian Variable 
print(a)

[-0.49979936  0.58180369 -0.01197106  0.89098541  1.82040112]


In [3]:
print(a.shape)

(5,)


In [4]:
#its neither coloumn nor row vector 
#Let's transpose a,it will look the same 
print(a.T)



[-0.49979936  0.58180369 -0.01197106  0.89098541  1.82040112]


In [5]:
print(np.dot(a,a.T))

4.696153479977589


# More practical approach

In [6]:
a = np.random.randn(5,1)
print(a)

[[ 0.32161183]
 [-0.01406373]
 [-1.73485669]
 [ 0.62547181]
 [ 0.24544314]]


In [7]:
print(a.T)

[[ 0.32161183 -0.01406373 -1.73485669  0.62547181  0.24544314]]


In [8]:
print(np.dot(a,a.T))

[[ 1.03434172e-01 -4.52306256e-03 -5.57950443e-01  2.01159135e-01
   7.89374195e-02]
 [-4.52306256e-03  1.97788551e-04  2.43985592e-02 -8.79646770e-03
  -3.45184653e-03]
 [-5.57950443e-01  2.43985592e-02  3.00972775e+00 -1.08510395e+00
  -4.25808680e-01]
 [ 2.01159135e-01 -8.79646770e-03 -1.08510395e+00  3.91214980e-01
   1.53517766e-01]
 [ 7.89374195e-02 -3.45184653e-03 -4.25808680e-01  1.53517766e-01
   6.02423366e-02]]
